### ISSUE TITLE
"no previous window" displayed in popup

### ISSUE THREAD

**Issue by von** [von/tmuxp-popup#1]
This seems to be a known issue with tmuxp: tmux-python/tmuxp#364

Workaround [from that issue's thread](https://github.com/tmux-python/tmuxp/issues/364#issuecomment-706946717) is to add a second window to the popup configuration file with one pane that just runs exit. Example file:

```
session_name: example
windows:
- window_name: terminal
  panes:
  - pane
- window_name: exit
  panes:
  - exit
```
